sudo: required

language:
  - java

services:
  - docker

jdk:
  - oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  # openshift
  - sudo sh -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-precise main" > /etc/apt/sources.list.d/docker.list'
  - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - sudo apt-get update
  - sudo apt-key update
  - sudo apt-get -qqy -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install docker-engine=1.11.1-0~precise
  - sudo apt-get install wget -y
  - sudo sed -i 's:DOCKER_OPTS=":DOCKER_OPTS="--insecure-registry 172.30.0.0/16 :g' /etc/default/docker
  - sudo mv /bin/findmnt /bin/findmnt.backup
  - sudo cat /etc/default/docker
  - sudo /etc/init.d/docker restart
  - wget https://github.com/openshift/origin/releases/download/v1.3.3/openshift-origin-client-tools-v1.3.3-bc17c1527938fa03b719e1a117d584442e3727b8-linux-64bit.tar.gz -O /tmp/oc.tar.gz
  - mkdir /tmp/ocdir && tar -C /tmp/ocdir -xvvf /tmp/oc.tar.gz
  - sudo mv /tmp/ocdir/*/oc /usr/bin/

script:
  # run tests
  - docker version
  - oc version
  - chmod +x oc-cluster-up.sh
  - ./oc-cluster-up.sh
  - ./gradlew build integTest

env:
  - GRADLE_VERSION=3.0
  - GRADLE_VERSION=3.1
  - GRADLE_VERSION=3.2
  - GRADLE_VERSION=3.3
  - GRADLE_VERSION=3.4
  - GRADLE_VERSION=3.5
  - GRADLE_VERSION=4.0
